language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install hypothesis pytest pytest-mock
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: collijk
  password:
    secure: B6WsVeTNBhIWZzqTqexLGdfWbAcZi+eOViOu8dF1RDFokzUIUaWXMl3p7nlq8t6f/Lxi9a8ddu5fALcM4K2oCNPVHLIioHe7jVH0Tz77g8YlgLfBbSj2KaX0ByBUm9wpdZOLErh/N/uP+8X1F2faILBqTpWAxvFUw4REC5OBttOx30ud6bAb4Hj85ouCI3a67v6ywT0ajSYBX+ZUcnnvDscX37HqsDhb8Asyy/wgMm8x/+3mfSdRFWWilAW7pH2k72rC5OJwS+YXwuyBaKmvDoYtG8eXKBES2hilyogYQBF5KiSjIts+ETJw5W3SHwMtVFsJ8ORUxccbC2zuiZCXxLOphIgNJD1JLbD3SA7YD9+ZVUbPYwWIdzZDO+0A/b0SRiVv/BxVKLNJj0xXDdRynIaX+94BGz8hStnWrt3SQhkjioL78Qob1+Y1HxVRh1AuasNbezfx8Lh4wM4+cbFPC98S48V9mT6jJ6nGPJiziSUo1DBb41ItnIc6ytvSOtLj1HfIL59W+mF78Ohfaki11kyHkEZ4ag0lpmFzEqxyFejl8SFfwYYqQ9sIi09gqmJAeYvLLYxhkXHZwMK2XKS0R7N1Bp1VPVrT9aFvGqyMM0fSt0/Y7ab1SCPSQRFimskApla9ZvZfCi/Cp4B1RmUkBDUk5jM5yHV83WeDXw6CGuQ=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/vivarium_inputs
    tags: true
