input_data:
    intermediary_data_cache_path: /share/scratch/users/{username}/cache
    gbd_publication_ids: [12,13,14,15,16,17] # GBD2015 capstone papers
    location_id: 180
    use_subregions: False
    gbd_round_id: 3
    j_drive: /home/j
    risk_factor_correlation_matrix_variation: location_180
