input_data:
    intermediary_data_cache_path: /share/scratch/users/{username}/cache
    location_id: 180
    use_subregions: False
    input_draw_number: 0
    gbd_round_id: 4
    j_drive: /home/j
    risk_factor_correlation_matrix_variation: location_180
