"""Mapping of GBD risks onto vivarium conventions."""

from .templates import Risk, Risks, Levels, Tmred, rid
from .causes import causes


risk_factors = Risks(
    unsafe_water_source=Risk(
        name='unsafe_water_source',
        gbd_id=rid(83),
        distribution='categorical',
        levels=Levels(
            cat1='unimproved and untreated',
            cat2='unimproved and chlorinated',
            cat3='unimproved and filtered',
            cat4='improved and untreated',
            cat5='improved and chlorinated',
            cat6='improved and filtered',
            cat7='piped and untreated',
            cat8='piped and chlorinated',
            cat9='piped and filtered',
        ),
        affected_causes=(causes.diarrhea, causes.typhoid_fever, causes.paratyphoid_fever),
    ),
    unsafe_sanitation=Risk(
        name='unsafe_sanitation',
        gbd_id=rid(84),
        distribution='categorical',
        levels=Levels(
            cat1='unimproved and untreated',
            cat2='improved',
            cat3='sewer',
        ),
        affected_causes=(causes.diarrhea, causes.typhoid_fever, causes.paratyphoid_fever),
    ),
    ambient_particulate_matter_pollution=Risk(
        name='ambient_particulate_matter_pollution',
        gbd_id=rid(86),
        distribution='unknown',
        affected_causes=(causes.lower_respiratory_infections, causes.tracheal_bronchus_and_lung_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.chronic_obstructive_pulmonary_disease),
        scale=1,
        max_rr=500,
        min_rr=0,
        max_val=500,
        min_val=0,

    ),
    household_air_pollution_from_solid_fuels=Risk(
        name='household_air_pollution_from_solid_fuels',
        gbd_id=rid(87),
        distribution='categorical',
        levels=Levels(
            cat1='exposed',
            cat2='unexposed',
        ),
        affected_causes=(causes.lower_respiratory_infections, causes.tracheal_bronchus_and_lung_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.chronic_obstructive_pulmonary_disease, causes.cataract),
    ),
    ambient_ozone_pollution=Risk(
        name='ambient_ozone_pollution',
        gbd_id=rid(88),
        distribution='unknown',
        affected_causes=(causes.chronic_obstructive_pulmonary_disease,),
        tmred=Tmred(
            distribution='uniform',
            min=30,
            max=50,
            inverted=False,
        ),
        scale=10,
        max_rr=100,
        min_rr=0,
        max_val=100,
        min_val=0,
        max_var=100,
    ),
    residential_radon=Risk(
        name='residential_radon',
        gbd_id=rid(90),
        distribution='lognormal',
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
        tmred=Tmred(
            distribution='uniform',
            min=7,
            max=14.8,
            inverted=False,
        ),
        scale=1,
        max_rr=10000,
        min_rr=0,
        max_val=10000,
        min_val=0,
        max_var=10000,
    ),
    childhood_underweight=Risk(
        name='childhood_underweight',
        gbd_id=rid(94),
        distribution='categorical',
        levels=Levels(
            cat1='more than 3 std. dev. below target',
            cat2='2 to 3 std. dev. below target',
            cat3='1 to 2 std. dev. below target',
            cat4='less than 1 std. dev. below target',
        ),
        affected_causes=(causes.diarrhea, causes.lower_respiratory_infections, causes.measles,
                         causes.protein_energy_malnutrition),
    ),
    iron_deficiency=Risk(
        name='iron_deficiency',
        gbd_id=rid(95),
        distribution='normal',
        affected_causes=(causes.maternal_hemorrhage, causes.maternal_sepsis_and_other_infections,
                         causes.iron_deficiency_anemia),
        tmred=Tmred(
            distribution='unknown',
            min=0,
            max=0,
            inverted=True,
        ),
        scale=10,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=5000,
    ),
    vitamin_a_deficiency=Risk(
        name='vitamin_a_deficiency',
        gbd_id=rid(96),
        distribution='categorical',
        levels=Levels(
            cat1='deficient',
            cat2='not deficient',
        ),
        affected_causes=(causes.diarrhea, causes.measles,
                         # FIXME: these causes fail to pull RR data (at the least).
                         # causes.vitamin_a_deficiency
                         ),
    ),
    zinc_deficiency=Risk(
        name='zinc_deficiency',
        gbd_id=rid(97),
        distribution='categorical',
        levels=Levels(
            cat1='deficient',
            cat2='not deficient',
        ),
        affected_causes=(causes.diarrhea, causes.lower_respiratory_infections),
    ),
    secondhand_smoke=Risk(
        name='secondhand_smoke',
        gbd_id=rid(100),
        distribution='categorical',
        levels=Levels(
            cat1='exposed',
            cat2='unexposed',
        ),
        affected_causes=(causes.lower_respiratory_infections, causes.otitis_media,
                         causes.tracheal_bronchus_and_lung_cancer, causes.ischemic_heart_disease,
                         causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.chronic_obstructive_pulmonary_disease),
    ),
    alcohol_use=Risk(
        name='alcohol_use',
        gbd_id=rid(102),
        distribution='unknown',
        affected_causes=(causes.tuberculosis, causes.lower_respiratory_infections, causes.lip_and_oral_cavity_cancer,
                         causes.nasopharynx_cancer, causes.other_pharynx_cancer, causes.esophageal_cancer,
                         causes.colon_and_rectum_cancer, causes.liver_cancer_due_to_hepatitis_b,
                         causes.liver_cancer_due_to_hepatitis_c, causes.liver_cancer_due_to_alcohol_use,
                         causes.liver_cancer_due_to_other_causes, causes.larynx_cancer, causes.breast_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.hypertensive_heart_disease, causes.atrial_fibrillation_and_flutter,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_use,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_other_causes,
                         causes.pancreatitis, causes.epilepsy, causes.alcohol_use_disorders, causes.diabetes_mellitus,
                         causes.pedestrian_road_injuries, causes.cyclist_road_injuries,
                         causes.motorcyclist_road_injuries, causes.motor_vehicle_road_injuries, causes.falls,
                         causes.drowning, causes.fire_heat_and_hot_substances, causes.poisonings,
                         causes.unintentional_firearm_injuries, causes.unintentional_suffocation,
                         causes.other_exposure_to_mechanical_forces, causes.self_harm, causes.assault_by_firearm,
                         causes.assault_by_sharp_object, causes.assault_by_other_means),
        scale=1,
        max_rr=100,
        min_rr=0,
        max_val=100,
        min_val=0,
        max_var=100,
    ),
    high_total_cholesterol=Risk(
        name='high_total_cholesterol',
        gbd_id=rid(106),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease, causes.ischemic_stroke),
        tmred=Tmred(
            distribution='uniform',
            min=2.78,
            max=3.38,
            inverted=False,
        ),
        scale=1,
        max_rr=10,
        min_rr=0,
        max_val=20,
        min_val=0,
        max_var=10,
    ),
    high_systolic_blood_pressure=Risk(
        name='high_systolic_blood_pressure',
        gbd_id=rid(107),
        distribution='lognormal',
        affected_causes=(causes.rheumatic_heart_disease, causes.ischemic_heart_disease, causes.ischemic_stroke,
                         causes.hemorrhagic_stroke, causes.hypertensive_heart_disease,
                         causes.cardiomyopathy_and_myocarditis, causes.atrial_fibrillation_and_flutter,
                         causes.aortic_aneurysm, causes.peripheral_vascular_disease, causes.endocarditis,
                         causes.other_cardiovascular_and_circulatory_diseases,
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes),
        tmred=Tmred(
            distribution='uniform',
            min=110,
            max=115,
            inverted=False,
        ),
        scale=10,
        max_rr=210,
        min_rr=70,
        max_val=300,
        min_val=50,
        max_var=200,
    ),
    high_body_mass_index=Risk(
        name='high_body_mass_index',
        gbd_id=rid(108),
        distribution='beta',
        affected_causes=(causes.esophageal_cancer, causes.colon_and_rectum_cancer,
                         # FIXME: these causes fail to pull RR data (at the least).
                         # causes.liver_cancer_due_to_hepatitis_b
                         # causes.liver_cancer_due_to_hepatitis_c,
                         # causes.liver_cancer_due_to_alcohol_use,
                         # causes.liver_cancer_due_to_other_causes,
                         causes.gallbladder_and_biliary_tract_cancer, causes.pancreatic_cancer, causes.breast_cancer,
                         causes.uterine_cancer, causes.ovarian_cancer, causes.kidney_cancer, causes.thyroid_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.hypertensive_heart_disease, causes.diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes, causes.osteoarthritis,
                         causes.low_back_pain),
        tmred=Tmred(
            distribution='uniform',
            min=20,
            max=25,
            inverted=False,
        ),
        scale=5,
        max_rr=45,
        min_rr=20,
        max_val=50,
        min_val=10,
        max_var=50,
    ),
    low_bone_mineral_density=Risk(
        name='low_bone_mineral_density',
        gbd_id=rid(109),
        distribution='normal',
        affected_causes=(causes.pedestrian_road_injuries, causes.cyclist_road_injuries,
                         causes.motorcyclist_road_injuries, causes.motor_vehicle_road_injuries,
                         causes.other_road_injuries, causes.other_transport_injuries, causes.falls,
                         causes.other_exposure_to_mechanical_forces, causes.non_venomous_animal_contact,
                         causes.assault_by_other_means, causes.exposure_to_forces_of_nature),
        tmred=Tmred(
            distribution='uniform',
            min=1,
            max=1.3,
            inverted=True,
        ),
        scale=0.1,
        max_rr=10,
        min_rr=0,
        max_val=10,
        min_val=0,
        max_var=5,
    ),
    diet_low_in_fruits=Risk(
        name='diet_low_in_fruits',
        gbd_id=rid(111),
        distribution='lognormal',
        affected_causes=(causes.lip_and_oral_cavity_cancer, causes.nasopharynx_cancer, causes.other_pharynx_cancer,
                         causes.esophageal_cancer, causes.larynx_cancer, causes.tracheal_bronchus_and_lung_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.diabetes_mellitus),
        tmred=Tmred(
            distribution='uniform',
            min=200,
            max=300,
            inverted=True,
        ),
        scale=100,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=400,
    ),
    diet_low_in_vegetables=Risk(
        name='diet_low_in_vegetables',
        gbd_id=rid(112),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke),
        tmred=Tmred(
            distribution='uniform',
            min=340,
            max=500,
            inverted=True,
        ),
        scale=100,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=450,
    ),
    diet_low_in_whole_grains=Risk(
        name='diet_low_in_whole_grains',
        gbd_id=rid(113),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.diabetes_mellitus),
        tmred=Tmred(
            distribution='uniform',
            min=100,
            max=150,
            inverted=True,
        ),
        scale=50,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=150,
    ),
    diet_low_in_nuts_and_seeds=Risk(
        name='diet_low_in_nuts_and_seeds',
        gbd_id=rid(114),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease, causes.diabetes_mellitus),
        tmred=Tmred(
            distribution='uniform',
            min=16,
            max=25,
            inverted=True,
        ),
        scale=4.05,
        max_rr=500,
        min_rr=0,
        max_val=500,
        min_val=0,
        max_var=24,
    ),
    diet_low_in_milk=Risk(
        name='diet_low_in_milk',
        gbd_id=rid(115),
        distribution='lognormal',
        affected_causes=(causes.colon_and_rectum_cancer,),
        tmred=Tmred(
            distribution='uniform',
            min=350,
            max=520,
            inverted=True,
        ),
        scale=226.8,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=680,
    ),
    diet_high_in_red_meat=Risk(
        name='diet_high_in_red_meat',
        gbd_id=rid(116),
        distribution='lognormal',
        affected_causes=(causes.colon_and_rectum_cancer, causes.diabetes_mellitus),
        tmred=Tmred(
            distribution='uniform',
            min=18,
            max=27,
            inverted=False,
        ),
        scale=100,
        max_rr=100,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=1000,
    ),
    diet_high_in_processed_meat=Risk(
        name='diet_high_in_processed_meat',
        gbd_id=rid(117),
        distribution='lognormal',
        affected_causes=(causes.colon_and_rectum_cancer, causes.ischemic_heart_disease, causes.diabetes_mellitus),
        tmred=Tmred(
            distribution='uniform',
            min=0,
            max=4,
            inverted=False,
        ),
        scale=50,
        max_rr=1000,
        min_rr=0,
        max_val=1000,
        min_val=0,
        max_var=1000,
    ),
    diet_high_in_sugar_sweetened_beverages=Risk(
        name='diet_high_in_sugar_sweetened_beverages',
        gbd_id=rid(118),
        distribution='lognormal',
        affected_causes=(causes.esophageal_cancer, causes.colon_and_rectum_cancer,
                         causes.liver_cancer_due_to_hepatitis_b, causes.liver_cancer_due_to_hepatitis_c,
                         causes.liver_cancer_due_to_alcohol_use, causes.liver_cancer_due_to_other_causes,
                         causes.gallbladder_and_biliary_tract_cancer, causes.pancreatic_cancer, causes.breast_cancer,
                         causes.uterine_cancer, causes.ovarian_cancer, causes.kidney_cancer, causes.thyroid_cancer,
                         causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.hypertensive_heart_disease, causes.diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes, causes.osteoarthritis,
                         causes.low_back_pain),
        tmred=Tmred(
            distribution='uniform',
            min=0,
            max=5,
            inverted=False,
        ),
        scale=226.8,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=5000,
    ),
    diet_low_in_fiber=Risk(
        name='diet_low_in_fiber',
        gbd_id=rid(119),
        distribution='lognormal',
        affected_causes=(causes.colon_and_rectum_cancer, causes.ischemic_heart_disease),
        tmred=Tmred(
            distribution='uniform',
            min=19,
            max=28,
            inverted=True,
        ),
        scale=20,
        max_rr=100,
        min_rr=0,
        max_val=100,
        min_val=0,
        max_var=32,
    ),
    diet_low_in_seafood_omega_3_fatty_acids=Risk(
        name='diet_low_in_seafood_omega_3_fatty_acids',
        gbd_id=rid(121),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease,),
        tmred=Tmred(
            distribution='uniform',
            min=200,
            max=300,
            inverted=True,
        ),
        scale=100,
        max_rr=5000,
        min_rr=0,
        max_val=5000,
        min_val=0,
        max_var=1000,
    ),
    diet_low_in_polyunsaturated_fatty_acids=Risk(
        name='diet_low_in_polyunsaturated_fatty_acids',
        gbd_id=rid(122),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease,),
        tmred=Tmred(
            distribution='uniform',
            min=0.09,
            max=0.13,
            inverted=True,
        ),
        scale=0.05,
        max_rr=1,
        min_rr=0,
        max_val=1,
        min_val=0,
        max_var=0.149,
    ),
    diet_high_in_trans_fatty_acids=Risk(
        name='diet_high_in_trans_fatty_acids',
        gbd_id=rid(123),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease,),
        tmred=Tmred(
            distribution='uniform',
            min=0,
            max=0.01,
            inverted=False,
        ),
        scale=0.02,
        max_rr=1,
        min_rr=0,
        max_val=1,
        min_val=0,
        max_var=1,
    ),
    diet_high_in_sodium=Risk(
        name='diet_high_in_sodium',
        gbd_id=rid(124),
        distribution='lognormal',
        affected_causes=(causes.stomach_cancer, causes.rheumatic_heart_disease, causes.ischemic_heart_disease,
                         causes.ischemic_stroke, causes.hemorrhagic_stroke, causes.hypertensive_heart_disease,
                         causes.cardiomyopathy_and_myocarditis, causes.atrial_fibrillation_and_flutter,
                         causes.aortic_aneurysm, causes.peripheral_vascular_disease, causes.endocarditis,
                         causes.other_cardiovascular_and_circulatory_diseases,
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes),
        tmred=Tmred(
            distribution='uniform',
            min=1,
            max=5,
            inverted=False,
        ),
        scale=1,
        max_rr=50,
        min_rr=0,
        max_val=50,
        min_val=0,
        max_var=50,
    ),
    low_physical_activity=Risk(
        name='low_physical_activity',
        gbd_id=rid(125),
        distribution='categorical',
        levels=Levels(
            cat1='<600 METs',
            cat2='600-3999 METs',
            cat3='4000-7999 METs',
            cat4='>=8000 METs',
        ),
        affected_causes=(causes.colon_and_rectum_cancer, causes.breast_cancer, causes.ischemic_heart_disease,
                         causes.ischemic_stroke, causes.diabetes_mellitus),
    ),
    occupational_asthmagens=Risk(
        name='occupational_asthmagens',
        gbd_id=rid(128),
        distribution='categorical',
        levels=Levels(
            cat1='admin',
            cat2='technical',
            cat3='sales',
            cat4='agriculture',
            cat5='mining',
            cat6='transport',
            cat7='manufacturing',
            cat8='services',
            cat9='other',
        ),
        affected_causes=(causes.asthma,),
    ),
    occupational_particulate_matter_gases_and_fumes=Risk(
        name='occupational_particulate_matter_gases_and_fumes',
        gbd_id=rid(129),
        distribution='categorical',
        levels=Levels(
            cat1='high',
            cat2='low',
            cat3='none',
        ),
        affected_causes=(causes.chronic_obstructive_pulmonary_disease, causes.coal_workers_pneumoconiosis)
    ),
    occupational_noise=Risk(
        name='occupational_noise',
        gbd_id=rid(130),
        distribution='categorical',
        levels=Levels(
            cat1='high (>90dB)',
            cat2='low (85-90dB)',
            cat3='none',
        ),
        affected_causes=(causes.age_related_and_other_hearing_loss,),
    ),
    occupational_injuries=Risk(
        name='occupational_injuries',
        gbd_id=rid(131),
        distribution='unknown',
        affected_causes=(causes.pedestrian_road_injuries, causes.cyclist_road_injuries,
                         causes.motorcyclist_road_injuries, causes.motor_vehicle_road_injuries,
                         causes.other_road_injuries, causes.other_transport_injuries, causes.falls, causes.drowning,
                         causes.fire_heat_and_hot_substances, causes.poisonings, causes.unintentional_firearm_injuries,
                         causes.unintentional_suffocation, causes.other_exposure_to_mechanical_forces,
                         causes.venomous_animal_contact, causes.non_venomous_animal_contact,
                         causes.pulmonary_aspiration_and_foreign_body_in_airway, causes.foreign_body_in_eyes,
                         causes.foreign_body_in_other_body_part, causes.other_unintentional_injuries),
    ),
    occupational_ergonomic_factors=Risk(
        name='occupational_ergonomic_factors',
        gbd_id=rid(132),
        distribution='categorical',
        levels=Levels(
            cat1='professional, technical, and related',
            cat2='administrative and managerial',
            cat3='clerical and related',
            cat4='sales',
            cat5='service',
            cat6='agriculture, husbandry, and forestry',
            cat7='production, transport, and laborers',
            cat8='background',
        ),
        affected_causes=(causes.low_back_pain,)
    ),
    non_exclusive_breastfeeding=Risk(
        name='non_exclusive_breastfeeding',
        gbd_id=rid(136),
        distribution='categorical',
        levels=Levels(
            cat1='none',
            cat2='partial',
            cat3='predominant',
            cat4='exclusive',
        ),
        affected_causes=(causes.diarrhea, causes.lower_respiratory_infections),
    ),
    discontinued_breastfeeding=Risk(
        name='discontinued_breastfeeding',
        gbd_id=rid(137),
        distribution='categorical',
        levels=Levels(
            cat1='discontinued',
            cat2='continued',
        ),
        affected_causes=(causes.diarrhea,),
    ),
    drug_use_dependence_and_blood_borne_viruses=Risk(
        name='drug_use_dependence_and_blood_borne_viruses',
        gbd_id=rid(138),
        distribution='unknown',
        affected_causes=(causes.hiv_aids_tuberculosis, causes.hiv_aids_other_diseases, causes.hepatitis_b,
                         causes.hepatitis_c, causes.liver_cancer_due_to_hepatitis_b,
                         causes.liver_cancer_due_to_hepatitis_c,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b,
                         causes.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c,
                         causes.opioid_use_disorders, causes.cocaine_use_disorders, causes.amphetamine_use_disorders,
                         causes.cannabis_use_disorders, causes.other_drug_use_disorders),
    ),
    suicide_due_to_drug_use_disorders=Risk(
        name='suicide_due_to_drug_use_disorders',
        gbd_id=rid(140),
        distribution='unknown',
        affected_causes=(causes.self_harm,),
    ),
    high_fasting_plasma_glucose_continuous=Risk(
        name='high_fasting_plasma_glucose_continuous',
        gbd_id=rid(141),
        distribution='lognormal',
        affected_causes=(causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         # FIXME causes.diabetes_mellitus,  This cause fails to pull data.
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes),
        tmred=Tmred(
            distribution='uniform',
            min=4.88488,
            max=5.301205,
            inverted=False,
        ),
        scale=1,
        max_rr=10,
        min_rr=3.8857,
        max_val=10,
        min_val=0,
        max_var=30,
    ),
    high_fasting_plasma_glucose_categorical=Risk(
        name='high_fasting_plasma_glucose_categorical',
        gbd_id=rid(142),
        distribution='categorical',
        levels=Levels(
            cat1='diabetic',
            cat2='not diabetic',
        ),
        affected_causes=(causes.tuberculosis, causes.peripheral_vascular_disease),
    ),
    low_glomerular_filtration_rate=Risk(
        name='low_glomerular_filtration_rate',
        gbd_id=rid(143),
        distribution='categorical',
        levels=Levels(
            cat1='stage 5 ckd',
            cat2='stage 4 ckd',
            cat3='stage 3 ckd',
        ),
        affected_causes=(causes.ischemic_heart_disease, causes.ischemic_stroke, causes.hemorrhagic_stroke,
                         causes.peripheral_vascular_disease, causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes, causes.gout),
    ),
    occupational_exposure_to_asbestos=Risk(
        name='occupational_exposure_to_asbestos',
        gbd_id=rid(150),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.larynx_cancer, causes.tracheal_bronchus_and_lung_cancer, causes.ovarian_cancer,
                         causes.mesothelioma),
    ),
    occupational_exposure_to_arsenic=Risk(
        name='occupational_exposure_to_arsenic',
        gbd_id=rid(151),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_beryllium=Risk(
        name='occupational_exposure_to_beryllium',
        gbd_id=rid(153),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_cadmium=Risk(
        name='occupational_exposure_to_cadmium',
        gbd_id=rid(154),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_chromium=Risk(
        name='occupational_exposure_to_chromium',
        gbd_id=rid(155),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_diesel_engine_exhaust=Risk(
        name='occupational_exposure_to_diesel_engine_exhaust',
        gbd_id=rid(156),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_secondhand_smoke=Risk(
        name='occupational_exposure_to_secondhand_smoke',
        gbd_id=rid(157),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_formaldehyde=Risk(
        name='occupational_exposure_to_formaldehyde',
        gbd_id=rid(158),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.nasopharynx_cancer,),
    ),
    occupational_exposure_to_nickel=Risk(
        name='occupational_exposure_to_nickel',
        gbd_id=rid(159),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_polycyclic_aromatic_hydrocarbons=Risk(
        name='occupational_exposure_to_polycyclic_aromatic_hydrocarbons',
        gbd_id=rid(160),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_silica=Risk(
        name='occupational_exposure_to_silica',
        gbd_id=rid(161),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.tracheal_bronchus_and_lung_cancer,),
    ),
    occupational_exposure_to_sulfuric_acid=Risk(
        name='occupational_exposure_to_sulfuric_acid',
        gbd_id=rid(162),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.larynx_cancer,),
    ),
    smoking_sir_approach=Risk(
        name='smoking_sir_approach',
        gbd_id=rid(165),
        distribution='categorical',
        levels=Levels(
            cat1='SIR',
            cat2='1-SIR',
        ),
        affected_causes=(causes.lip_and_oral_cavity_cancer, causes.nasopharynx_cancer, causes.esophageal_cancer,
                         causes.stomach_cancer, causes.colon_and_rectum_cancer, causes.liver_cancer_due_to_hepatitis_b,
                         causes.liver_cancer_due_to_hepatitis_c, causes.liver_cancer_due_to_alcohol_use,
                         causes.liver_cancer_due_to_other_causes, causes.pancreatic_cancer, causes.larynx_cancer,
                         causes.tracheal_bronchus_and_lung_cancer, causes.cervical_cancer, causes.kidney_cancer,
                         causes.bladder_cancer, causes.chronic_obstructive_pulmonary_disease, causes.silicosis,
                         causes.asbestosis, causes.coal_workers_pneumoconiosis, causes.other_pneumoconiosis,
                         causes.interstitial_lung_disease_and_pulmonary_sarcoidosis,
                         causes.other_chronic_respiratory_diseases, ),
    ),
    smoking_prevalence_approach=Risk(
        name='smoking_prevalence_approach',
        gbd_id=rid(166),
        distribution='categorical',
        levels=Levels(
            cat1='Smoker (5 year lag)',
            cat2='Nonsmoker (5 year lag)',
        ),
        affected_causes=(causes.tuberculosis, causes.lower_respiratory_infections, causes.ischemic_heart_disease,
                         causes.ischemic_stroke, causes.hemorrhagic_stroke, causes.hypertensive_heart_disease,
                         causes.atrial_fibrillation_and_flutter, causes.aortic_aneurysm,
                         causes.peripheral_vascular_disease, causes.other_cardiovascular_and_circulatory_diseases,
                         causes.asthma, causes.peptic_ulcer_disease, causes.diabetes_mellitus,
                         causes.rheumatoid_arthritis, causes.cataract, causes.macular_degeneration,
                         causes.pedestrian_road_injuries, causes.cyclist_road_injuries,
                         causes.motorcyclist_road_injuries, causes.motor_vehicle_road_injuries,
                         causes.other_road_injuries, causes.other_transport_injuries, causes.falls,
                         causes.other_exposure_to_mechanical_forces, causes.non_venomous_animal_contact,
                         causes.assault_by_other_means, causes.exposure_to_forces_of_nature),
    ),
    intimate_partner_violence_exposure_approach=Risk(
        name='intimate_partner_violence_exposure_approach',
        gbd_id=rid(167),
        distribution='categorical',
        levels=Levels(
            cat1='exposed',
            cat2='unexposed',
        ),
        affected_causes=(causes.maternal_abortion_miscarriage_and_ectopic_pregnancy, causes.major_depressive_disorder,
                         causes.dysthymia, causes.self_harm, causes.assault_by_firearm, causes.assault_by_sharp_object,
                         causes.assault_by_other_means),
    ),
    intimate_partner_violence_direct_paf_approach=Risk(
        name='intimate_partner_violence_direct_paf_approach',
        gbd_id=rid(168),
        distribution='unknown',
        affected_causes=(causes.assault_by_firearm, causes.assault_by_sharp_object, causes.assault_by_other_means),
    ),
    unsafe_sex=Risk(
        name='unsafe_sex',
        gbd_id=rid(170),
        distribution='unknown',
        affected_causes=(causes.hiv_aids_tuberculosis, causes.hiv_aids_other_diseases, causes.syphilis,
                         causes.chlamydia, causes.gonorrhea, causes.trichomoniasis, causes.genital_herpes,
                         causes.other_sexually_transmitted_disease, causes.cervical_cancer),
    ),
    intimate_partner_violence_hiv_paf_approach=Risk(
        name='intimate_partner_violence_hiv_paf_approach',
        gbd_id=rid(201),
        distribution='unknown',
        affected_causes=(causes.hiv_aids_tuberculosis, causes.hiv_aids_other_diseases),
    ),
    occupational_exposure_to_trichloroethylene=Risk(
        name='occupational_exposure_to_trichloroethylene',
        gbd_id=rid(237),
        distribution='categorical',
        levels=Levels(
            cat1='high exposure',
            cat2='low exposure',
            cat3='no exposure',
        ),
        affected_causes=(causes.kidney_cancer,),
    ),
    no_handwashing_with_soap=Risk(
        name='no_handwashing_with_soap',
        gbd_id=rid(238),
        distribution='categorical',
        levels=Levels(
            cat1='no handwashing with soap',
            cat2='handwashing with soap',
        ),
        affected_causes=(causes.diarrhea, causes.typhoid_fever, causes.paratyphoid_fever,
                         causes.lower_respiratory_infections),
    ),
    childhood_wasting=Risk(
        name='childhood_wasting',
        gbd_id=rid(240),
        distribution='categorical',
        levels=Levels(
            cat1='more than 3 std. dev. below target',
            cat2='2 to 3 std. dev. below target',
            cat3='1 to 2 std. dev. below target',
            cat4='less than 1 std. dev. below target',
        ),
        affected_causes=(causes.diarrhea, causes.lower_respiratory_infections, causes.measles,
                         # FIXME: The following cause fails to pull RR data
                         # causes.protein_energy_malnutrition
                         ),
    ),
    childhood_stunting=Risk(
        name='childhood_stunting',
        gbd_id=rid(241),
        distribution='categorical',
        levels=Levels(
            cat1='more than 3 std. dev. below target',
            cat2='2 to 3 std. dev. below target',
            cat3='1 to 2 std. dev. below target',
            cat4='less than 1 std. dev. below target',
        ),
        affected_causes=(causes.diarrhea, causes.lower_respiratory_infections, causes.measles),
    ),
    lead_exposure_in_blood=Risk(
        name='lead_exposure_in_blood',
        gbd_id=rid(242),
        distribution='unknown',
        affected_causes=(causes.idiopathic_developmental_intellectual_disability,),
    ),
    lead_exposure_in_bone=Risk(
        name='lead_exposure_in_bone',
        gbd_id=rid(243),
        distribution='lognormal',
        affected_causes=(causes.rheumatic_heart_disease, causes.ischemic_heart_disease, causes.ischemic_stroke,
                         causes.hemorrhagic_stroke, causes.hypertensive_heart_disease,
                         causes.cardiomyopathy_and_myocarditis, causes.atrial_fibrillation_and_flutter,
                         causes.aortic_aneurysm, causes.peripheral_vascular_disease, causes.endocarditis,
                         causes.other_cardiovascular_and_circulatory_diseases,
                         causes.chronic_kidney_disease_due_to_diabetes_mellitus,
                         causes.chronic_kidney_disease_due_to_hypertension,
                         causes.chronic_kidney_disease_due_to_glomerulonephritis,
                         causes.chronic_kidney_disease_due_to_other_causes),
        tmred=Tmred(
            distribution='uniform',
            min=0,
            max=20,
            inverted=False,
        ),
        scale=10,
        max_rr=500,
        min_rr=0,
        max_val=500,
        min_val=0,
        max_var=500,
    ),
    childhood_sexual_abuse_against_females=Risk(
        name='childhood_sexual_abuse_against_females',
        gbd_id=rid(244),
        distribution='categorical',
        levels=Levels(
            cat1='exposed',
            cat2='unexposed',
        ),
        affected_causes=(causes.alcohol_use_disorders, causes.major_depressive_disorder, causes.dysthymia,
                         causes.self_harm),
    ),
    childhood_sexual_abuse_against_males=Risk(
        name='childhood_sexual_abuse_against_males',
        gbd_id=rid(245),
        distribution='categorical',
        levels=Levels(
            cat1='exposed',
            cat2='unexposed',
        ),
        affected_causes=(causes.alcohol_use_disorders, causes.major_depressive_disorder, causes.dysthymia,
                         causes.self_harm),
    ),
)
